drop database if exists auction;
create database auction;
use auction;

create table customer(
customer_id int not null auto_increment,
fname varchar(30) not null,
lname varchar(30) not null,
country varchar(30) not null,
address varchar (30) not null,
password varchar(30) not null, 
email varchar(30) unique not null,
city varchar(30) not null,
phone varchar (30) not null, 
primary key (customer_id));

create table seller(
seller_id int not null auto_increment,
fname varchar(30) not null,
lname varchar(30) not null,
country varchar(30) not null,
address varchar (30) not null,
password varchar(30) not null, 
email varchar(30) unique not null,
city varchar(30) not null,
phone varchar (30) not null, 
primary key (seller_id));


create table seller_product(
product_id int not null auto_increment,
categories enum("SPORTS", "HOUSES", "WATCHES", "VEHICLES", "JEWELRY", "ELECTRONICS", "ARTS", "CARS"),
image_id int not null unique,
primary key(product_id));

create table sports(
sports_id int not null auto_increment,
product_id int not null,
sport_type enum ("Gym Equipments", "Video Games", "Consoles", "Basketball", "Football", "Training Wear"),
primary key(sports_id),
foreign key (product_id) references seller_product (product_id));

create table sport_football(
football_id int not null auto_increment,
gender enum ("Male", "Female", "Unisex"),
size enum ("Small","Medium", "Large"),
sports_id int not null,
Type enum ("Shoes", "Jerseys", "Socks","Balls"),
brand varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
title varchar (20),
image_id int not null,
minimum_bid_price int not null,
buy_price int not null,
conditions enum ("Brand New", "Ghanaian Used", "Foreign Used"),
location enum("ACCRA", "KUMASI", "CAPE COAST", "TAKORADI", "TEMALE", "UPPER EAST", "UPPER WEST", "VOLTA REGION", "KOFORIDUA", "WA", "BOLGATANGA"),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(football_id),
foreign key (sports_id) references sports(sports_id),
foreign key (image_id) references seller_product (image_id));

create table sport_weight(
weight_id int not null auto_increment,
sports_id int not null,
weight int not null, 
brand enum ("Bodygrip", "Strauss", "Cockatoo","Aurion", "AmazonBasics", "Bowflex","SPRI", "Cap Barbell"),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
title varchar (20),
image4 varchar(255),
image_id int not null,
minimum_bid_price int not null,
buy_price int not null,
conditions enum ("Brand New", "Ghanaian Used", "Foreign Used"),
location enum("ACCRA", "KUMASI", "CAPE COAST", "TAKORADI", "TEMALE", "UPPER EAST", "UPPER WEST", "VOLTA REGION", "KOFORIDUA", "WA", "BOLGATANGA"),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(weight_id),
foreign key (sports_id) references sports(sports_id),
foreign key (image_id) references seller_product (image_id));

create table sport_consoles(
console_id int not null auto_increment,
sports_id int not null,
brand enum ("PS4", "PS5", "Xbox One","Xbox 360", "Xbox Series X"),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
title varchar (20),
image_id int not null,
minimum_bid_price int not null,
buy_price int not null,
conditions enum ("Brand New", "Ghanaian Used", "Foreign Used"),
location enum("ACCRA", "KUMASI", "CAPE COAST", "TAKORADI", "TEMALE", "UPPER EAST", "UPPER WEST", "VOLTA REGION", "KOFORIDUA", "WA", "BOLGATANGA"),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(console_id),
foreign key (sports_id) references sports(sports_id),
foreign key (image_id) references seller_product (image_id));

create table sport_games(
game_id int not null auto_increment,
sports_id int not null,
Type enum ("PS4", "PS5", "Xbox One","Xbox 360", "Xbox Series X"),
Game varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
title varchar (20),
minimum_bid_price int not null,
buy_price int not null,
conditions enum ("Brand New", "Ghanaian Used", "Foreign Used"),
location enum("ACCRA", "KUMASI", "CAPE COAST", "TAKORADI", "TEMALE", "UPPER EAST", "UPPER WEST", "VOLTA REGION", "KOFORIDUA", "WA", "BOLGATANGA"),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(game_id),
foreign key (sports_id) references sports(sports_id),
foreign key (image_id) references seller_product (image_id));

create table sport_basketball(
basketball_id int not null auto_increment,
gender enum ("Male", "Female", "Unisex"),
size enum ("Small","Medium", "Large"),
sports_id int not null,
Type enum ("Shoes", "Top", "Pant", "Short", "Full-kit", "Socks","Balls"),
brand varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
title varchar (20),
image_id int not null,
minimum_bid_price int not null,
buy_price int not null,
conditions enum ("Brand New", "Ghanaian Used", "Foreign Used"),
location enum("ACCRA", "KUMASI", "CAPE COAST", "TAKORADI", "TEMALE", "UPPER EAST", "UPPER WEST", "VOLTA REGION", "KOFORIDUA", "WA", "BOLGATANGA"),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(basketball_id),
foreign key (sports_id) references sports(sports_id),
foreign key (image_id) references seller_product (image_id));

create table sport_training_wear(
training_id int not null auto_increment,
gender enum ("Male", "Female", "Unisex"),
size enum ("Small","Medium", "Large"),
sports_id int not null,
Type enum ("Shoes", "Top", "Pant", "Short", "Full-kit", "Socks","Balls"),
brand varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
minimum_bid_price int not null,
title varchar (20),
buy_price int not null,
conditions enum ("Brand New", "Ghanaian Used", "Foreign Used"),
location enum("ACCRA", "KUMASI", "CAPE COAST", "TAKORADI", "TEMALE", "UPPER EAST", "UPPER WEST", "VOLTA REGION", "KOFORIDUA", "WA", "BOLGATANGA"),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(training_id),
foreign key (sports_id) references sports(sports_id),
foreign key (image_id) references seller_product (image_id));


Create table houses(
house_id int not null auto_increment,
product_id int not null,
bedroom_num int (30),
bathroom_num int (30),
facilities varchar (150),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
house_type varchar(25),
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
title varchar (20),
location varchar(30),
house_size varchar(30),
house_address varchar(30),
color varchar(20),
description varchar(200),
primary key(house_id),
foreign key (product_id) references sports(product_id),
foreign key (image_id) references seller_product (image_id));

Create table arts(
art_id int not null auto_increment,
product_id int not null,
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
art_type varchar(25),
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
title varchar (20),
location varchar(30),
size varchar(30),
address varchar(30),
color varchar(20),
description varchar(200),
primary key(art_id),
foreign key (product_id) references seller_product(product_id),
foreign key (image_id) references seller_product (image_id));

Create table watches(
watch_id int not null auto_increment,
product_id int not null,
gender varchar(30),
brand varchar(30),
category varchar(30),
facilities varchar (150),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
title varchar (20),
image_id int not null,
material_type varchar(25),
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
location varchar(30),
color varchar(20),
house_address varchar(30),
description varchar(200),
primary key(watch_id),
foreign key (product_id) references seller_product(product_id),
foreign key (image_id) references seller_product (image_id));

create table bidding(
bid_count int not null auto_increment,
customer_id int not null,
item_id int not null,
min_bid_price int not null,
product_name varchar(50) not null,
buy_price int not null,
days datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
primary key(bid_count));