drop database if exists auction;
create database auction;
use auction;

create table customer(
customer_id int not null auto_increment,
fname varchar(30) not null,
lname varchar(30) not null,
country varchar(30) not null,
address varchar (30) not null,
password varchar(30) not null, 
email varchar(30) unique not null,
city varchar(30) not null,
phone varchar (30) not null unique, 
primary key (customer_id));

create table seller(
seller_id int not null auto_increment,
fname varchar(30) not null,
lname varchar(30) not null,
country varchar(30) not null,
address varchar (30) not null,
password varchar(30) not null, 
email varchar(30) unique not null,
city varchar(30) not null,
phone varchar (30) not null unique, 
primary key (seller_id));


create table seller_product(
product_id int not null auto_increment,
categories enum("SPORTS", "HOUSES", "WATCHES", "VEHICLES", "JEWELRY", "ELECTRONICS", "ARTS", "CARS"),
image_id int not null unique,
primary key(product_id));

create table sports(
sports_id int not null auto_increment,
product_id int not null,
sport_type enum ("Gym Equipments", "Basketball", "Football", "Training Wear"),
primary key(sports_id),
foreign key (product_id) references seller_product (product_id));

create table sport_football(
football_id int not null auto_increment,
gender varchar(30),
size varchar (30),
sports_id int not null,
material_type varchar(30),
brand varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
title varchar (20),
image_id int not null,
minimum_bid_price int not null,
buy_price int not null,
conditions varchar (30),
location varchar (30),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(football_id),
foreign key (sports_id) references sports(sports_id),
foreign key (image_id) references seller_product (image_id));

create table sport_weight(
weight_id int not null auto_increment,
sports_id int not null,
weight int not null, 
brand varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
title varchar (20),
image4 varchar(255),
image_id int not null,
minimum_bid_price int not null,
buy_price int not null,
conditions varchar (30),
location varchar (30),
description varchar(200),
color varchar(20),
primary key(weight_id),
foreign key (sports_id) references sports(sports_id),
foreign key (image_id) references seller_product (image_id));

create table sport_basketball(
basketball_id int not null auto_increment,
gender enum ("Male", "Female", "Unisex"),
size varchar (30),
sports_id int not null,
material_type varchar(30),
brand varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
title varchar (20),
image_id int not null,
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
location varchar(30),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(basketball_id),
foreign key (sports_id) references sports(sports_id),
foreign key (image_id) references seller_product (image_id));

create table sport_training_wear(
training_id int not null auto_increment,
gender varchar(30),
size varchar (30),
sports_id int not null,
material_type varchar( 30),
brand varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
minimum_bid_price int not null,
title varchar (20),
buy_price int not null,
conditions enum ("Brand New", "Ghanaian Used", "Foreign Used"),
location varchar (30),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(training_id),
foreign key (sports_id) references sports(sports_id),
foreign key (image_id) references seller_product (image_id));


Create table houses(
house_id int not null auto_increment,
product_id int not null,
bedroom_num int (30),
bathroom_num int (30),
facilities varchar (150),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
house_type varchar(25),
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
title varchar (20),
location varchar(30),
house_size varchar(30),
house_address varchar(30),
color varchar(20),
description varchar(200),
primary key(house_id),
foreign key (product_id) references sports(product_id),
foreign key (image_id) references seller_product (image_id));

Create table arts(
art_id int not null auto_increment,
product_id int not null,
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
art_type varchar(25),
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
title varchar (20),
location varchar(30),
size varchar(30),
address varchar(30),
color varchar(20),
description varchar(200),
primary key(art_id),
foreign key (product_id) references seller_product(product_id),
foreign key (image_id) references seller_product (image_id));

Create table jewelry(
art_id int not null auto_increment,
gender varchar(30), 
jewelry_type varchar (30),
material_type varchar (30),
product_id int not null,
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
art_type varchar(25),
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
title varchar (20),
location varchar(30),
size varchar(30),
address varchar(30),
color varchar(20),
description varchar(200),
primary key(art_id),
foreign key (product_id) references seller_product(product_id),
foreign key (image_id) references seller_product (image_id));

Create table watches(
watch_id int not null auto_increment,
product_id int not null,
gender varchar(30),
watch_brand varchar(30),
material_type varchar(30),
category varchar(30),
facilities varchar (150),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
title varchar (20),
image_id int not null,
material_type varchar(25),
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
location varchar(30),
color varchar(20),
address varchar(30),
description varchar(200),
primary key(watch_id),
foreign key (product_id) references seller_product(product_id),
foreign key (image_id) references seller_product (image_id));

create table electronics(
electronic_id int not null auto_increment,
product_id int not null,
sport_type enum ("Consoles", "Video Games", "Laptops", "Mobile Phones", "TV", "Speakers", "Headset & Airpods"),
primary key(electronics_id),
foreign key (product_id) references seller_product (product_id));

create table electronic_consoles(
console_id int not null auto_increment,
electronic_id int not null,
console_brand varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
title varchar (20),
image_id int not null,
minimum_bid_price int not null,
buy_price int not null,
conditions varchar (30),
location varchar (30),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(console_id),
foreign key (electronic_id) references electronics(electronic_id),
foreign key (image_id) references seller_product (image_id));

create table electronic_games(
game_id int not null auto_increment,
electronic_id int not null,
game_brand varchar (30),
Game varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
title varchar (20),
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
location varchar(30),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(game_id),
foreign key (electronic_id) references electronics(electronic_id),
foreign key (image_id) references seller_product (image_id));

create table electronic_laptops(
laptop_id int not null auto_increment,
electronic_id int not null,
laptop_brand varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
title varchar (20),
processor varchar (30),
ram size varchar (30),
screen size varchar (30),
storage varchar (30),
operating_system varchar (30), 
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
location varchar(30),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(game_id),
foreign key (electronic_id) references electronics(electronic_id),
foreign key (image_id) references seller_product (image_id));

create table electronic_phones(
phone_id int not null auto_increment,
electronic_id int not null,
phone_brand varchar (30),
storage varchar(30),
water_proof enum ("YES", "NO"),
ram varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
title varchar (20),
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
location varchar(30),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(game_id),
foreign key (electronic_id) references electronics(electronic_id),
foreign key (image_id) references seller_product (image_id));

create table electronic_tv(
tv_id int not null auto_increment,
electronic_id int not null,
tv_brand varchar (30),
size varchar (30),
display varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
title varchar (20),
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
location varchar(30),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(tv_id),
foreign key (electronic_id) references electronics(electronic_id),
foreign key (image_id) references seller_product (image_id));

create table electronic_speakers(
speaker_id int not null auto_increment,
electronic_id int not null,
speaker_brand varchar (30),
water_proof enum ("YES", "NO"),
size varchar (30),
display varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
title varchar (20),
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
location varchar(30),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(speaker_id),
foreign key (electronic_id) references electronics(electronic_id),
foreign key (image_id) references seller_product (image_id));

create table electronic_headset(
headset_id int not null auto_increment,
electronic_id int not null,
tv_brand varchar (30),
headest_type enum ("Airpods", "Headset"),
water_proof enum ("YES", "NO"),
size varchar (30),
display varchar (30),
image1 varchar(255),
image2 varchar(255),
image3 varchar(255),
image4 varchar(255),
image_id int not null,
title varchar (20),
minimum_bid_price int not null,
buy_price int not null,
conditions varchar(30),
location varchar(30),
address varchar(30),
description varchar(200),
color varchar(20),
primary key(headset_id),
foreign key (electronic_id) references electronics(electronic_id),
foreign key (image_id) references seller_product (image_id));


create table bidding(
bid_count int not null auto_increment,
customer_id int not null,
item_id int not null,
min_bid_price int not null,
product_name varchar(50) not null,
buy_price int not null,
days datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
primary key(bid_count));
